const FETCH_PROJECT_REQUEST = 'FETCH_PROJECT_REQUEST';
const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS';
const FETCH_PROJECT_FAILURE = 'FETCH_PROJECT_FAILURE';

const FETCH_PHONE_REQUEST = 'FETCH_PHONE_REQUEST';
const FETCH_PHONE_SUCCESS = 'FETCH_PHONE_SUCCESS';
const FETCH_PHONE_FAILURE = 'FETCH_PHONE_FAILURE';

export {
    FETCH_PROJECT_REQUEST,
    FETCH_PROJECT_SUCCESS,
    FETCH_PROJECT_FAILURE,
    FETCH_PHONE_REQUEST,
    FETCH_PHONE_SUCCESS,
    FETCH_PHONE_FAILURE,
};
